### PR TITLE
Feature/add more resources

### PR DESCRIPTION
**Pull request by GuidoMaggio**
PR created for review

At the current status:

- GitHub action workflow failing
- Some embedded sites do not display correctly, see discussion below

### CODE REVIEW

**Comment by GuidoMaggio** [comment]
[_site.zip](https://github.com/miraisolutions/covid-19-gallery/files/10012476/_site.zip)

Uploaded local _site for @riccardoporreca

**Comment by GuidoMaggio** [comment]
GHA to be updated

**Comment by GuidoMaggio** [comment]
See comment in https://github.com/miraisolutions/meetings/issues/227

**Comment by riccardoporreca** [comment]
**Status update as of 2022-12-20**

The following resources cannot be rendered in the gallery, since they are not meant to be embedded in an `iframe`

- COVID-19 Switzerland BAG Dashboard by BAG [[source](https://opendata.swiss/en/dataset/covid-19-schweiz/)]
- COVID-19 Kanton Zurich Dashboard by Kanton ZH Statistiches Amt [[source](https://zh.ch/de/politik-staat/opendata.html?keyword=ogd#/details/671@gesundheitsdirektion-kanton-zuerich/)]
- COVID-19 USA Dashboard by Prevent Epidemics [[source](https://preventepidemics.org/covid19/indicators/)]
- COVID-19 Italy Dashboard by Istituto Superiore di Sanità [[source](https://www.iss.it/richiesta-dati-covid19)]
- COVID-19 United Kingdom Dashboard by Office for National Statistics [[source](https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/conditionsanddiseases/articles/coronaviruscovid19/latestinsights)]
  - Most graphics there can be individually embedded, perhaps we could go for the embeddable https://www.ons.gov.uk/visualisations/dvc1470/tiles6/wrapper/
- COVID-19 Denmark Dashboard by Danish Health Authority [[source](https://www.sst.dk/da/corona/tal-og-overvaagning#5)]
- COVID-19 Austria Dashboard by Österreichische Agentur für Gesundheit und Ernährungssicherheit GmbH [[source](https://covid19-dashboard.ages.at/)]

**Comment by GuidoMaggio** [comment]
Check at legal disclaimers:

- [x] [COVID-19 Global Shiny Dashboard](http://127.0.0.1:19837/rmd_output/1/global-eth-corona-data-ch.html) by ETH Zurich
Nothing mentioned, only their responsibility
- [x] [COVID-19 Global Dashboard](http://127.0.0.1:19837/rmd_output/1/global-jhu-covid-19-global.html) by Johns Hopkins University Center for Systems Science and Engineering
Nothing mentioned
- [x] [COVID-19 Global Dashboard](http://127.0.0.1:19837/rmd_output/2/global-ourworldindata.html) by ourworldindata.org
Open source
https://ourworldindata.org/faqs
- [x] [COVID-19 Global Worldometers Data](http://127.0.0.1:19837/rmd_output/2/global-worldometers-coronavirus.html) by worldometers.info
Nothing mentioned
- [ ] [COVID-19 Switzerland BAG Dashboard](http://127.0.0.1:19837/rmd_output/3/switzerland-bag-corona-data-ch.html) by BAG
https://www.admin.ch/gov/en/start/terms-and-conditions.html
It should be ok although this sentence
_Copyright and any other rights relating to texts, illustrations, photos or any other data available on the Federal authorities' websites are the exclusive property of the federal authorities or of any other expressly mentioned owners. Any reproduction requires the prior written consent of the copyright holder._
- [x] [COVID-19 Switzerland Dashboard](http://127.0.0.1:19837/rmd_output/3/switzerland-daenuprobst-corona-data-ch.html) by Daniel Probst
All open source
- [x] [COVID-19 Kanton Zurich Dashboard](http://127.0.0.1:19837/rmd_output/3/switzerland-kanton-zh-corona-data-ch.html) by Kanton ZH Statistiches Amt
It should be fine
https://www.zh.ch/de/nutzungshinweise.html
Jede weitere Verwendung von Inhalten aus den kantonalen Internetseiten und insbesondere das Einbinden (über Frames oder Inlinelinks) in andere Seiten ist nur mit Einverständnis der Rechteinhabenden gestattet.
- [x] [COVID-19 Switzerland Dashboard](http://127.0.0.1:19837/rmd_output/3/switzerland-salzer-corona-data-ch.html) by Robert Salzer
Open source
- [x] [COVID-19 USA Dashboard](http://127.0.0.1:19837/rmd_output/3/usa-cnn-coronavirus-data.html) by CNN
Nothing found
- [x] [COVID-19 Italy Dashboard](http://127.0.0.1:19837/rmd_output/3/italy-gedi-covid-19-italy.html) by GEDI
Nothing found
- [x] [COVID-19 Italy Dashboard](http://127.0.0.1:19837/rmd_output/3/italy-iss-covid-19-italy.html) by Istituto Superiore di Sanità
Open data
https://form.agid.gov.it/view/44834069-2840-4630-8c41-3ccc889fb72f/
- [x] [COVID-19 Italy Dashboard](http://127.0.0.1:19837/rmd_output/4/italy-sole24ore-covid-19-italy.html) by Sole 24 Ore
Nothing found
- [x] [COVID-19 Germany Dashboard](http://127.0.0.1:19837/rmd_output/4/germany-rki.html) by Robert Koch Institute
Nothing found
- [x] [COVID-19 United Kingdom Dashboard](http://127.0.0.1:19837/rmd_output/4/uk-gov.uk-coronavirus-data.html) by UK Health Security Agency
Seems open
https://coronavirus.data.gov.uk/details/compliance
- [x] [COVID-19 United Kingdom Dashboard](http://127.0.0.1:19837/rmd_output/4/uk-ons-coronavirus-data.html) by Office for National Statistics
fine
https://www.ons.gov.uk/help/termsandconditions
- [x] [COVID-19 France Dashboard](http://127.0.0.1:19837/rmd_output/4/france-gov-coronavirus-data.html) by Ministère des Solidarités et de la Santé et Santé publique France
Opens ource
https://github.com/etalab/covid19-dashboard
- [x] [COVID-19 Denmark Dashboard](http://127.0.0.1:19837/rmd_output/4/dk-gov-coronavirus-data.html) by Danish Health Authority
Nothing found
- [x] [COVID-19 Austria Dashboard](http://127.0.0.1:19837/rmd_output/4/austria-gov-coronavirus-data.html) by Österreichische Agentur für Gesundheit und Ernährungssicherheit GmbH
Open source
https://covid19-dashboard.ages.at/barrierefreiheitserklaerung_en.html

**Comment by GuidoMaggio** [comment]
When building locally the latest version, upon clicking on a link a window opens also externally, causing sometimes problems

**Comment by GuidoMaggio** [comment]
We can then finalise and publish it, making sure where the site cant be embedded the link works correctly

**Comment by GuidoMaggio** [comment]
@riccardoporreca I managed to generate the site correctly, it works fine.
Those sites that cant be embedded do not appear but it is fine.

**Comment by riccardoporreca** [comment]
> Those sites that cant be embedded do not appear but it is fine.

Fine for now, although not ideal. I created as dedicated #6, but we can go with this first.

**Review by riccardoporreca — APPROVED** [review]

**Pull request merged**
